### ISSUE TITLE
Package doesn't appear with Install Package (ST2)

### ISSUE THREAD

**Issue by mikeerickson** [gnarula/sublime-laravelgenerator#10]
Trying to install this plugin with ST2 and the package doesnt appear when attempting to install package.  Guessing the only way to install would be manually at this point (for both ST2 and ST3)

**Comment by gnarula** [comment]
I have submitted a pull request for this plugin to be accepted into Package
Control. We'll have to wait until it gets merged.

**Comment by gnarula** [comment]
It should appear on Package Control now.

**Comment by GaryJones** [comment]
Can confirm that it does indeed appear in Package Control :+1:
