### ISSUE TITLE
PHP path on windows

### ISSUE THREAD

**Issue by RomainGoncalves** [gnarula/sublime-laravelgenerator#11]
Hi, 

I've been trying to add my path to php.exe in the file you mentionned. I copied it to the user folder and tried different combination to make it work. Nothing seems to work.
I've tried:

C:/xampp/php
C:\xampp\php (gives me a parsing error on save)
C:/xampp/php/php.exe
C:/\/xampp/\/php

**Comment by jrmadsen67** [comment]
ditto - have pulled again after the latest fix; will not run on Windows.

I restart Sublime Text 2 each time I make a change.

If you can tell me what to do to debug, I'll try to help

Will try some more, report any luck

**Comment by gnarula** [comment]
Try this:

```
C:\\xampp\\php\\php.exe
```

Windows uses backward slashes that need to be escaped with a backward slash.

**Comment by jrmadsen67** [comment]
Thank you - I wasn't including the .exe file

```
"php_path": "C:\\UniServer\\usr\\local\\php\\php.exe" 
```

spoke too soon - get a command prompt flash, but no files

**Comment by gnarula** [comment]
What command did you run and does the status bar report any error? Also, is there anything in the console (Ctrl+`)?

**Comment by jrmadsen67** [comment]
After Gaurav was kind enough to debug with me for a bit, I stumbled on it:

Jeffrey Way's tutorial here:
http://net.tutsplus.com/tutorials/tools-and-tips/pro-workflow-in-laravel-and-sublime-text/

simply sends you to composer to grab the files, but there is some setup you need to do. If you follow the instructions on his gitub page, should work out for you:

https://github.com/JeffreyWay/Laravel-4-Generators

Also: For Windows users, try including php.exe in the "php_path"

(ex: "php_path": "C:/UniServer/usr/local/php/php.exe")

**Comment by RomainGoncalves** [comment]
Thanks gnarula, with the proper escaping it now works for me. I can create resources and use artisan from sublime.

Thanks

BTW: proper escaping for me is: C:\xampp\php\php.exe
