### ISSUE TITLE
IOError - Command aborted

### ISSUE THREAD

**Issue by LarsJK** [gnarula/sublime-laravelgenerator#13]
I am trying to use the generator but it fails when it tries to execute the commands (after i have entered the inputs..)

I get this error message:

IOError - Command aborted

**Comment by gnarula** [comment]
Is `php_path` set properly in the configuration?

**Comment by LarsJK** [comment]
Thanks that fixed it.. I'm on OS X so i just skipped step 3 in the installation guide..
But I have php in /usr/local/bin/php..
