### ISSUE TITLE
Every generate method fails

### ISSUE THREAD

**Issue by BastianHofmann** [gnarula/sublime-laravelgenerator#17]
All generate methods will display: "Oh snap! generate:name_of_method failed".

Installed the package via package control.

**Comment by gnarula** [comment]
Does the artisan file exist at the root of the project? Is path to php set properly?

**Comment by BastianHofmann** [comment]
Artisan is in the root directory.

I'm using MAMP, so there are two php installations. That could be the problem.

**Comment by BastianHofmann** [comment]
Updated: cli "php" is now using php by MAMP instead of OSX default php.

Laravel Artsian Command is now working, the rest is not.

**Comment by BastianHofmann** [comment]
Looks like it's a problem with my installation of php. Has nothing to do with the sublime text plugins. Thanks for your time.

**Comment by gnarula** [comment]
try executing `which php` in the terminal and set the same path in the configuration. If the generators work in the command line they should do so in the plugin as well provided the same php binary is being used.

**Comment by BastianHofmann** [comment]
"which php" returns /usr/local/bin/php but I added the following line to .profile:

export PATH=/Applications/MAMP/bin/php/php5.4.10/bin:$PATH

 So in terminal "php" will now use MAMP's version. I tried php -v and it gave me the Version number MAMP uses.

php artisan generate:model dog // Works in terminal; In sublime text: "Oh snap! generate:model failed"

When I make a artisan command in sublime text: "generate:model dog" it returns "artisan generate:model successfully created", but doesn't actually create it.

**Comment by khrrsn** [comment]
I can confirm I have the same exact problem, I do know the problem went away last time I went a few commits back in Laravel 4.

**Comment by BastianHofmann** [comment]
That's odd, but I would rather use the latest version of laravel and use the generator tools in Terminal.

Update:
I ran "which php" and added the path (/usr/local/bin/php) to laravelgenerators.sublime-settings, didn't work. Also tried setting the path directly to MAMP's php.

**Comment by gnarula** [comment]
@BastianHofmann Does the last commit add any verbosity to the error message?

**Comment by RyanHavoc** [comment]
I'm also having this issue. Originally I was getting a "requires mcrypt" so I updated the php_path in laravelgenerators.sublime-settings to point to the correct version of PHP on my system. Now the same command still fails but there's no additional message... stumped.

**Comment by sebastienv** [comment]
I had the same problem, but that was my fault. I forgot to do this step : add 'Way\Generators\GeneratorsServiceProvider' to providers in 'app/config/app.php'.

**Comment by lutsifer** [comment]
exact same problem here..

**Comment by stephengarn** [comment]
"laravelgenerators.sublime-settings" should be "laravelgenerator.sublime-settings" and can be accessed through Preferences->Browse Packages...

**Comment by stephengarn** [comment]
So this worked for me...Preferences->Browse Packages->Laravel Generator -----> open laravelgenerator.sublime-settings and edit the path file to your .bash_profile.

**Comment by Vrutin** [comment]
It might be due to not including: 'Way\Generators\GeneratorsServiceProvider' in the app.php
