### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by JeffreyWay** [gnarula/sublime-laravelgenerator#2]
Hey, Gaurav - 

So here are my notes, after testing the plugin:
- Would there be some way to open the file immediately after running the command? So I generate a model, Dog; the Artisan command is triggered; and then the models/Dog.php file is immediately opened. I'd imagine this might be a bit difficult, because the Artisan command is doing all of the logic. Does ST offer some way to determine the most recently edited/created file?
- I'm not sure if you need the placeholder text for the popup. It's just one more thing to delete. Better to have a more descriptive label. See below.
- Can you split the generate:migration fill-in into two inputs...to make it a bit easier? migrationName --fields="fields" is a little confusing. Maybe one for "Migration Name:" and the next for "Table Fields," minus the --fields="" bit. You'd add that form them. So, I'd run generate:migration, type "create_users_table", hit enter, type "name:string", hit enter, and then artisan generate:migration --fields="name:string" command would be triggered.
- The generate:resource command should allow for fields as well. Run generate:resource, type "dog", hit enter, label says "Any fields? (column:type format)," I type "name:string", hit enter, and then artisan generate:resource --fields="name:string" command is triggered.

Here are the fill_in labels:
- **Model**: Enter the name of the model
- **View**: Enter the file name of the view
- **Migration**: Two fill-ins. "Enter the migration name", "Table fields in the column:type format (optional)"
- **Seed**: Enter the table name that you're seeding.
- **Test**: Enter the file name for the test
- **Resource**: two fill-ins: "Enter the singular name of the resource", "Table fields in the column:type format (optional)"

**Comment by gnarula** [comment]
Thanks for your suggestions Jeffrey.
- I think this can be done by catching artisan's output to STDOUT and using some regex to get matches for .php files.
- Yes, the extra key-stroke isn't worth it indeed
- Here's how I plan to do this: The config file will require an optional Boolean argument named fields (will default to False if not specified). If the fields argument is set to True, the plugin will show an input bar for the fields after the fill_in has been entered by the user. This way in future if we add another command that requires fields as the parameter we just edit some JSON.

Thanks for the labels, I'll commit them right away.

**Comment by JeffreyWay** [comment]
I think this one is just about done! Great work.

The only tiny thing I noticed was that, when you run generate:resource, that command is responsible for generating a lot of files, and we probably don't want to open all of them. Maybe open nothing in the case of that one command.

**Comment by gnarula** [comment]
93afe2eb1b fixes this
