### ISSUE TITLE
Doesn't work under Windows 7 and sublime 2

### ISSUE THREAD

**Issue by drakakisgeo** [gnarula/sublime-laravelgenerator#21]
I put this in the path
"php_path": "C:/wamp/bin/php/php5.3.8/"

or this

"php_path": "C:\wamp\bin\php\php5.3.8\"

Console says this after command:

found 13 files for base name Main.sublime-menu
Traceback (most recent call last):
  File ".\generate.py", line 51, in call_artisan
  File ".\subprocess.py", line 633, in **init**
  File ".\subprocess.py", line 842, in _execute_child
WindowsError: [Error 5] Access is denied

**Comment by samvasko** [comment]
There is a same the issue just before this one, 
please close it and just copy it there

**Comment by drakakisgeo** [comment]
Its not the same error, thats why I opened another one. WindowsError: [Error 5] Access is denied

**Comment by gnarula** [comment]
@lollypopgr add php.exe at the end of the path (assuming thats the name of the executable). If the error still persists, it might be an issue with permissions

**Comment by drakakisgeo** [comment]
Hi gnarula, great work by the way! Tried to add this, but it didn't work.

**Comment by gnarula** [comment]
Try running sublime as administrator (just for the sake of testing this). This would ascertain if it is a permission issue.

**Comment by rahulparekh** [comment]
@gnarula - Running as an administrator worked, indeed! When I tried running it without the admin privileges, it ran artisan commands without any issue (because artisan doesn't need admin rights, I think) while generating models, resource etc failed.

Anyway, I'm using this on win7 x64 with Xampp.

This is my settings file:

{
    "php_path": "C:/xampp/php/php.exe"
}

Hope this helps people who are having issues running it on windows.

**Comment by drakakisgeo** [comment]
Strange @rahulparekh because my user has admin rights and I really can't make it work.

**Comment by coldfuzion** [comment]
Just to confirm - 

adding 

{
"php_path": "C:/xampp/php/php.exe"
}

and running as administrator ( sublime text 2 program ) worked for me. It is a permission problem somewhere. This does fix it. If anyone knows why this exists on windows 7 let me know?

**Comment by goldnetonline** [comment]
The issue i had was, when trying to run any of the generation tools, what I get is 'Artisan not found' on the Sublime text command.

I tried running window 7 as Administrator, I still get the same errors, I( am using XAMPP

Any help please, Thanks

**Comment by gnarula** [comment]
Are you working on a laravel project on Sublime Text (the folder should be
there in the sidebar) and is the artisan binary in the same folder?

**Comment by goldnetonline** [comment]
This is making me cry right now, I think the stuff seems to be working but all I get is Artisan not found, funny enough artisan is at the root of my project. I dont really know what I am missing, the snippet is also working as explained in the workflow window.

**Comment by imroue** [comment]
I have the same issue with "Artisan not found" using Mac Osx and I know it's there because I can run it manually, but not through Sublime Text generator

**Comment by goldnetonline** [comment]
Ok, but @imroue I believe you can run it via the console, if you can do that, carry on. The generator is a bomb on its own. imagine the generate:scaffold command. just like all the hell of work done for you, what a workflowic way to speed things. Thanks jeff.

**Comment by imroue** [comment]
@goldnet, so are you saying you gave up on the plugin?

**Comment by gnarula** [comment]
@imroue let's create a separate issue for each platform. I checked the plugin on Linux (Sublime Text 3 build 3047) and OS X (Sublime Text 2 Build 2221) and it works fine. More information would be appreciated in a separate issue.

P.S. Windows is next

**Comment by goldnetonline** [comment]
@imroue on sublime text 2 yes, but I now use the generator on the console, it works perfectly for me, and I dont really have the speed issue since my console is always open. 

Also I wish I could donate to the author of the generator someday, there are some things the generator taught me that even speed things up with learning laravel. Thanks again Jeffery. I'll make some donation as soon as I can

**Comment by drakakisgeo** [comment]
I just stopped using it under windows.

**Comment by Perkin5** [comment]
Hi lollypopgr - I have the exact same problem. Did you ever get it sorted out?

**Comment by drakakisgeo** [comment]
I stopped using it. Started to work on ubuntu in general, so things like that doesn't exist there.

**Comment by Perkin5** [comment]
I can't think of anything else to try. Sigh...

**Comment by reuf** [comment]
Same issue here. Sad to have this happen.

**Comment by jack6800** [comment]
There is a scenario that your sublime project included many folders may caused "Artisan not found" issue, I'm using win7 64 and fix this issue by add php.exe just like what Rahulparekh did and has only folder that include Artisan.
