### ISSUE TITLE
Unable to install on Mac

### ISSUE THREAD

**Issue by fuzaylov** [gnarula/sublime-laravelgenerator#22]
Sublime Laravel Generator plugin is not found on Sublime.

**Comment by gnarula** [comment]
Is Package Control installed? If yes, I rechecked the repos and the plugin does exist in the repos. If it fails for some reason, please install the plugin manually by cloning the repo in the Packages folder manually.

**Comment by rahulparekh** [comment]
If you are searching for "Sublime Laravel Generator" it says not found as it is named "Laravel Generator". It happened to me at first too.

**Comment by fuzaylov** [comment]
Cloning manually helped. Thanks, Gnarula!
