### ISSUE TITLE
artisan not found

### ISSUE THREAD

**Issue by imroue** [gnarula/sublime-laravelgenerator#30]
Wondering if anyone ran into this issue:
I installed laravel and this cool laravelgenerator sublime plugin.
i am able to generate views with artisan on the command line, but when i try to run the plugin via sublime, i get a message saying "artisan not found".

It is already in the project folder.

Any ideas?

**Comment by gnarula** [comment]
![Laravel Project Structure](http://i.imgur.com/QOMqeJk.png)

Is the project structure like this? A few points to note:
- The laravel project is the topmost folder in the ST Window
- Artisan is one level inside the folder

**Comment by imroue** [comment]
Yes @gnarula this is exactly what I have. I can even run the commands manually, but it's sublime text plugin that is refusing to.

**Comment by gnarula** [comment]
Please add

### ST3

``` python
print(self.PROJECT_PATH)
```

### ST2

``` python
print self.PROJECT_PATH
```

after line 34 in generate.py (keeping the indent of the else block). This should print the Project Directory in the console (Cmd + ` to view). Is it correct?

**Comment by imroue** [comment]
Yes it is correct.. it's my project folder.. under that I have a folder called "shop_site".. and under that I have all the laravel stuff which includes artisan
![untitled](https://f.cloud.github.com/assets/4925574/763034/9da5b7b6-e7f5-11e2-8e6b-9fc9d0182f4c.jpg)

**Comment by gnarula** [comment]
There, try making shop_site the first folder instead

**Comment by imroue** [comment]
Ah that worked, thanks.. I was trying to keep multiple projects in my sublime workspace.. i guess that doesn't work.
thanks!

**Comment by War777** [comment]
A very useful answer @gnarula Thanks, it really worked!!!

**Comment by dreammonkey** [comment]
hi! This solves the issue indeed, but is there a way can point the script to the laravel folder / artisan cli ? I like to keep the root of my project one level higher, i.e. the root of the repo. that way I can easily reference other files like readme.md etc ... 

thanks !

**Comment by skygravity** [comment]
Make sure you open project directly in your Code Editor. For example: if i open **htdocs/**  in Sublime and try to make controller in mysite then artisan not found, if i open project in **htdocs/mysite** then everything is ok. 
Don't
![notfound](https://cloud.githubusercontent.com/assets/8436772/10117005/1c0ee694-6450-11e5-94e9-aaded3afdea1.PNG)
Do
![artisan_works](https://cloud.githubusercontent.com/assets/8436772/10117007/34896992-6450-11e5-918c-e9dc64987947.PNG)

Hope it helps for future generations.

**Comment by KingGeneral** [comment]
hello sir, if you are still facing this issue try like mine , although its still manual

remember this only for 1 project : (so you need to change artisan path per your project)
in your package setting, 

me using xampp, and for my artisan path i copy it bare

{
    "php_path": "C:/xampp/php/php.exe",
    "artisan_path": "C:\\xampp\\htdocs\\_laravel\\todoapp\\artisan"
}

still confused ? summon me in :3

**Comment by geraldmuvengei06** [comment]
skygravity, thanks dude, I did what you've said and it has worked.
