### ISSUE TITLE
windows no space between arguments

### ISSUE THREAD

**Issue by isimmons** [gnarula/sublime-laravelgenerator#9]
One more minor window bug. It won't allow spaces between field arguments. 

fails

```
fname:string, lname:string, age:integer
```

creates successfully 

```
fname:string,lname:string,age:integer
```

**Comment by gnarula** [comment]
This one's due to `posix=False` change for Windows in the previous commit. In non-posix behavior, quotes between words are not considered.

We've a catch 22 situation here...

**Comment by gnarula** [comment]
That should fix this issue hopefully.

**Comment by isimmons** [comment]
Working beautifully for me now. Thanks
